---
abstract: "Get IP/IPList Info (location, as number, etc)\r"
author:
  - 'Abby Pan <abbypan@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Simple-IPInfo
requires:
  Data::Validate::IP: '0'
  JSON: '0'
  Memoize: '0'
  SimpleR::Reshape: '0'
resources:
  repository: https://github.com/abbypan/Simple-IPInfo.git
version: '0.05'
